apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampledemo-deployment
  labels:
    app: sampledemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampledemo
  template:
    metadata:
      labels:
        app: sampledemo 
    spec:
      containers:
      - name: sampledemo
        image: robinksk/sample-eks:1
        ports:
        - containerPort: 9090
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: sampledemo-service
spec:
  selector:
    app: sampledemo 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
